version: 2
updates:
  - package-ecosystem: bundler
    directory: '/'
    schedule:
      interval: weekly
      time: '08:00'
      timezone: America/New_York
    open-pull-requests-limit: 10

  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: weekly
      time: '08:00'
      timezone: America/New_York
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: weekly
      time: '08:00'
      timezone: America/New_York
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
      time: '08:00'
      timezone: America/New_York
